# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'three.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 492)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    /*background-color:qlineargradient(x1:0,y0:1,x1:0,y1:1,stop:0 rgb(19,61,112), stop:1 rgb(54,124,173));*/\n"
"background-color:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgb(23,58,103), stop:1 rgb(184,249,255));\n"
"border-radius:18px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(185, 450))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = PushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_3.setStyleSheet("/*QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font-family:华文新魏;\n"
"font: bold 25px;\n"
"border-radius:18px;\n"
"}\n"
"QPushButton:hover {\n"
"                background-color: #1976d2;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #0d47a1;\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }*/")
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setShortcut("")
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setMinimumSize(QtCore.QSize(171, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = PushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton.setStyleSheet("/*QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font-family:华文新魏;\n"
"font: bold 25px;\n"
"border-radius:18px;\n"
"border-width: 2px;\n"
"/*border-style: outset;*/\n"
"/*}\n"
"QPushButton:hover {\n"
"                background-color: #1976d2;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #0d47a1;\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }*/")
        self.pushButton.setIconSize(QtCore.QSize(30, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = PushButton(self.frame_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_2.setStyleSheet("/*QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font-family:华文新魏;\n"
"font: bold 25px;\n"
"border-radius:18px;\n"
"}\n"
"QPushButton:hover {\n"
"                background-color: #1976d2;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #0d47a1;\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }*/")
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_7 = PushButton(self.frame_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_7.setStyleSheet("/*QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font-family:华文新魏;\n"
"font: bold 25px;\n"
"border-radius:18px;\n"
"}\n"
"QPushButton:hover {\n"
"                background-color: #1976d2;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #0d47a1;\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }*/")
        self.pushButton_7.setIconSize(QtCore.QSize(20, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.pushButton_6 = PushButton(self.frame_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_6.setStyleSheet("/*QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font-family:华文新魏;\n"
"font: bold 25px;\n"
"border-radius:18px;\n"
"}\n"
"QPushButton:hover {\n"
"                background-color: #1976d2;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: #0d47a1;\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }*/")
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 400))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget{\n"
"    border-image: url(:/images/Qtdesigner/images/无标题.jpg);\n"
"/*border-image: url(:/images/Qtdesigner/images/dna-7090994_1280.jpg);*/\n"
"    /*border-image: url(:/images/Qtdesigner/images/背景3.png);*/}\n"
"")
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setStyleSheet("QLabel{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 45px;\n"
"    min-width:2em;\n"
"    /*color:#000000; /*字体颜色*/\n"
"    font-family:黑体/*华文新魏*/;\n"
"    padding: 2px;\n"
"    color:rgb(255,255,255);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget{\n"
"/*border-image: url(:/images/Qtdesigner/images/lab-217043_1280.jpg);*/\n"
"border-image: url(:/images/Qtdesigner/images/1.jpg);\n"
"border-radius:10px;\n"
"}")
        self.page_2.setObjectName("page_2")
        self.gridLayout = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = LineEdit(self.page_2)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 2px;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.lineEdit_3 = LineEdit(self.page_2)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 2px;\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.pushButton_5 = PushButton(self.page_2)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }\n"
"\n"
"")
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setStyleSheet("QLabel{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 25px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 5px;\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QWidget{\n"
"border-image: url(:/images/Qtdesigner/images/covid-19-4982914_1280.jpg);\n"
"    border-image: url(:/images/Qtdesigner/images/technology-4905257_1280.jpg);\n"
"border-radius:10px;\n"
"}")
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = LineEdit(self.page_3)
        self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: rgba(255,255,255); /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.pushButton_4 = PushButton(self.page_3)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 20px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"                padding-left: 12px;\n"
"                padding-top: 10px;\n"
"            }\n"
"")
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setStyleSheet("QLabel{\n"
"    border-image: url();  /*新增位置*/\n"
"    /*background-color: #473C8B; /*背景色*/ \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:5px; /*边界圆滑*/\n"
"    border-color: #8B7355;\n"
"    font: bold 25px;\n"
"    min-width:2em;\n"
"    color:#000000; /*字体颜色*/\n"
"    font-family:华文新魏;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("")
        self.page_4.setObjectName("page_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = PlainTextEdit(self.page_4)
        self.plainTextEdit.setStyleSheet("border-style: outset;")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 4, 0, 1, 4)
        self.radioButton_2 = RadioButton(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 1, 2, 1, 2)
        self.radioButton = RadioButton(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 1, 0, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.page_4)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.progressBar = ProgressBar(self.frame_5)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"        border: 2px solid grey;\n"
"        border-radius: 5px;\n"
"        text-align: center;\n"
"    }\n"
"\n"
"    QProgressBar::chunk {\n"
"        /*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #FF6600, stop:1 #FF0000);*/\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #96c8ff, stop:1 #326496);\n"
"    }")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.gridLayout_2.addWidget(self.frame_5, 7, 0, 1, 4)
        self.pushButton_10 = PushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 3, 0, 1, 4)
        self.pushButton_8 = PushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setToolTip("")
        self.pushButton_8.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 9, 0, 1, 2)
        self.pushButton_9 = PushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setToolTip("")
        self.pushButton_9.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 9, 2, 1, 2)
        self.radioButton.raise_()
        self.frame_5.raise_()
        self.radioButton_2.raise_()
        self.plainTextEdit.raise_()
        self.pushButton_10.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_3, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<a target=\"_blank\" href=\"https://icons8.com/icon/TzMnSwiJW8HO/%E4%B8%BB%E9%A1%B5\">主页</a> icon by <a target=\"_blank\" href=\"https://icons8.com\">Icons8</a>"))
        self.pushButton_3.setText(_translate("MainWindow", "首页"))
        self.pushButton.setText(_translate("MainWindow", "△G(solv)"))
        self.pushButton_2.setText(_translate("MainWindow", "Tox21"))
        self.pushButton_7.setText(_translate("MainWindow", "待开发"))
        self.pushButton_6.setText(_translate("MainWindow", "批量导入"))
        self.label_3.setToolTip(_translate("MainWindow", "分子探长是一款分子性质预测软件"))
        self.label_3.setText(_translate("MainWindow", "分子探长"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入溶质smiles"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "请输入溶剂smiles"))
        self.pushButton_5.setText(_translate("MainWindow", "预测"))
        self.label.setText(_translate("MainWindow", "溶剂化自由能预测"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入分子smiles"))
        self.pushButton_4.setText(_translate("MainWindow", "预测"))
        self.label_2.setText(_translate("MainWindow", "基于Tox21的毒性预测"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "file content"))
        self.radioButton_2.setToolTip(_translate("MainWindow", "请导入具有列‘smiles’的文件"))
        self.radioButton_2.setText(_translate("MainWindow", "APPAT"))
        self.radioButton.setToolTip(_translate("MainWindow", "请导入具有列\'SoluteSMILES\'和列\'SolventSMILES\'的文件"))
        self.radioButton.setText(_translate("MainWindow", "CIGIN"))
        self.label_5.setText(_translate("MainWindow", "进度:"))
        self.pushButton_10.setToolTip(_translate("MainWindow", "请选择.csv或.txt文件"))
        self.pushButton_10.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_8.setText(_translate("MainWindow", "开始预测"))
        self.pushButton_9.setText(_translate("MainWindow", "保存"))
from qfluentwidgets import LineEdit, PlainTextEdit, ProgressBar, PushButton, RadioButton
import qrc_rc
